/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package example.avro;
@org.apache.avro.specific.AvroGenerated
public enum game implements org.apache.avro.generic.GenericEnumSymbol<game> {
  ARCHER, WITCHER, RIDER, SABER  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"game\",\"namespace\":\"example.avro\",\"symbols\":[\"ARCHER\",\"WITCHER\",\"RIDER\",\"SABER\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
